.TH "src/include/balance.h" 3 "Thu Jan 13 2022" "Simulazione Transazioni" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/balance.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBbalance\fP (int budget)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int balance (int budget)"

.PP
Definition at line \fB1\fP of file \fBbalance\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Simulazione Transazioni from the source code\&.
