.TH "block_t" 3 "Thu Jan 13 2022" "Simulazione Transazioni" \" -*- nroff -*-
.ad l
.nh
.SH NAME
block_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <common\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBtransaction\fP \fBtransList\fP [\fBSO_BLOCK_SIZE\fP]"
.br
.ti -1c
.RI "unsigned int \fBblockIndex\fP"
.br
.ti -1c
.RI "struct \fBblock\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBblock\fP * \fBprev\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB139\fP of file \fBcommon\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "unsigned int blockIndex"

.PP
Definition at line \fB142\fP of file \fBcommon\&.h\fP\&.
.SS "struct \fBblock\fP* next"

.PP
Definition at line \fB143\fP of file \fBcommon\&.h\fP\&.
.SS "struct \fBblock\fP* prev"

.PP
Definition at line \fB144\fP of file \fBcommon\&.h\fP\&.
.SS "\fBtransaction\fP transList[\fBSO_BLOCK_SIZE\fP]"

.PP
Definition at line \fB141\fP of file \fBcommon\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Simulazione Transazioni from the source code\&.
