.TH "src/common.c" 3 "Thu Jan 13 2022" "Simulazione Transazioni" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/common.c
.SH SYNOPSIS
.br
.PP
\fC#include 'include/common\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBledger\fP * \fBledger_init\fP ()"
.br
.ti -1c
.RI "\fBblock\fP * \fBnew_block\fP ()"
.br
.ti -1c
.RI "void \fBadd_transaction_to_block\fP (\fBblock\fP *\fBblock\fP, \fBtransaction\fP *newTrans, int index)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void add_transaction_to_block (\fBblock\fP * block, \fBtransaction\fP * newTrans, int index)"

.PP
Definition at line \fB46\fP of file \fBcommon\&.c\fP\&.
.SS "\fBledger\fP * ledger_init ()"

.PP
Definition at line \fB3\fP of file \fBcommon\&.c\fP\&.
.SS "\fBblock\fP * new_block ()"

.PP
Definition at line \fB24\fP of file \fBcommon\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Simulazione Transazioni from the source code\&.
