.TH "src/utils/debug.c" 3 "Thu Jan 13 2022" "Simulazione Transazioni" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/utils/debug.c
.SH SYNOPSIS
.br
.PP
\fC#include 'debug\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdbg_printf\fP (const char *fmt,\&.\&.\&.)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void dbg_printf (const char * fmt,  \&.\&.\&.)"

.PP
Definition at line \fB3\fP of file \fBdebug\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Simulazione Transazioni from the source code\&.
