.TH "src/utils/debug.h" 3 "Thu Jan 13 2022" "Simulazione Transazioni" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/utils/debug.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdarg\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTRACE\fP(x)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdbg_printf\fP (const char *fmt,\&.\&.\&.)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TRACE(x)"

.PP
Definition at line \fB12\fP of file \fBdebug\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void dbg_printf (const char * fmt,  \&.\&.\&.)"

.PP
Definition at line \fB3\fP of file \fBdebug\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Simulazione Transazioni from the source code\&.
