.TH "ledger_t" 3 "Thu Jan 13 2022" "Simulazione Transazioni" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ledger_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <common\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBblock\fP * \fBhead\fP"
.br
.ti -1c
.RI "unsigned int \fBregistryCurrSize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB148\fP of file \fBcommon\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBblock\fP* head"

.PP
Definition at line \fB150\fP of file \fBcommon\&.h\fP\&.
.SS "unsigned int registryCurrSize"

.PP
Definition at line \fB151\fP of file \fBcommon\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Simulazione Transazioni from the source code\&.
