.TH "src/include/master.h" 3 "Thu Jan 13 2022" "Simulazione Transazioni" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/master.h
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmake_arguments\fP (int *IPCarray, char *argv[])"
.br
.ti -1c
.RI "pid_t \fBspawn_user\fP (char *argv[])"
.br
.ti -1c
.RI "pid_t \fBspawn_node\fP (char *argv[])"
.br
.ti -1c
.RI "void \fBshared_memory_objects_init\fP (int *shared_memory_objects_IDs)"
.br
.ti -1c
.RI "void \fBsemaphores_init\fP ()"
.br
.ti -1c
.RI "void \fBmake_ipc_array\fP (int *IPC_objects_IDs)"
.br
.ti -1c
.RI "void \fBmaster_interrupt_handle\fP (int signum)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void make_arguments (int * IPCarray, char * argv[])"

.SS "void make_ipc_array (int * IPC_objects_IDs)"

.PP
Definition at line \fB175\fP of file \fBmaster\&.c\fP\&.
.SS "void master_interrupt_handle (int signum)"

.PP
Definition at line \fB188\fP of file \fBmaster\&.c\fP\&.
.SS "void semaphores_init ()"

.PP
Definition at line \fB167\fP of file \fBmaster\&.c\fP\&.
.SS "void shared_memory_objects_init (int * shared_memory_objects_IDs)"

.PP
Definition at line \fB111\fP of file \fBmaster\&.c\fP\&.
.SS "pid_t spawn_node (char * argv[])"

.PP
Definition at line \fB88\fP of file \fBmaster\&.c\fP\&.
.SS "pid_t spawn_user (char * argv[])"

.PP
Definition at line \fB65\fP of file \fBmaster\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Simulazione Transazioni from the source code\&.
