.TH "message" 3 "Thu Jan 13 2022" "Simulazione Transazioni" \" -*- nroff -*-
.ad l
.nh
.SH NAME
message
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <common\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "long \fBmtype\fP"
.br
.ti -1c
.RI "\fBtransaction\fP \fBuserTrans\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB132\fP of file \fBcommon\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "long mtype"

.PP
Definition at line \fB134\fP of file \fBcommon\&.h\fP\&.
.SS "\fBtransaction\fP userTrans"

.PP
Definition at line \fB135\fP of file \fBcommon\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Simulazione Transazioni from the source code\&.
