.TH "node_t" 3 "Thu Jan 13 2022" "Simulazione Transazioni" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <common\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBavailable\fP, \fBfull\fP }"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "pid_t \fBpid\fP"
.br
.ti -1c
.RI "enum node_t:: { \&.\&.\&. }  \fBstatus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB105\fP of file \fBcommon\&.h\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIavailable \fP\fP
.TP
\fB\fIfull \fP\fP
.PP
Definition at line \fB108\fP of file \fBcommon\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "pid_t pid"

.PP
Definition at line \fB107\fP of file \fBcommon\&.h\fP\&.
.SS "enum  { \&.\&.\&. }  status"


.SH "Author"
.PP 
Generated automatically by Doxygen for Simulazione Transazioni from the source code\&.
