.TH "src/nodes.c" 3 "Thu Jan 13 2022" "Simulazione Transazioni" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/nodes.c
.SH SYNOPSIS
.br
.PP
\fC#include <time\&.h>\fP
.br
\fC#include 'include/nodes\&.h'\fP
.br
\fC#include 'include/common\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBparameters\fP * \fBpar\fP"
.br
.ti -1c
.RI "\fBuser\fP * \fBusersPID\fP"
.br
.ti -1c
.RI "\fBnode\fP * \fBnodesPID\fP"
.br
.ti -1c
.RI "\fBledger\fP * \fBmainLedger\fP"
.br
.ti -1c
.RI "int \fBsemID\fP"
.br
.ti -1c
.RI "int \fBqueueID\fP"
.br
.ti -1c
.RI "pid_t \fBmyPID\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line \fB58\fP of file \fBnodes\&.c\fP\&.
.SH "Variable Documentation"
.PP 
.SS "\fBledger\fP* mainLedger"

.PP
Definition at line \fB17\fP of file \fBnodes\&.c\fP\&.
.SS "pid_t myPID"

.PP
Definition at line \fB22\fP of file \fBnodes\&.c\fP\&.
.SS "\fBnode\fP* nodesPID"

.PP
Definition at line \fB16\fP of file \fBnodes\&.c\fP\&.
.SS "struct \fBparameters\fP* par"

.PP
Definition at line \fB14\fP of file \fBnodes\&.c\fP\&.
.SS "int queueID"

.PP
Definition at line \fB20\fP of file \fBnodes\&.c\fP\&.
.SS "int semID"

.PP
Definition at line \fB19\fP of file \fBnodes\&.c\fP\&.
.SS "\fBuser\fP* usersPID"

.PP
Definition at line \fB15\fP of file \fBnodes\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Simulazione Transazioni from the source code\&.
