.TH "src/include/nodes.h" 3 "Thu Jan 13 2022" "Simulazione Transazioni" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/nodes.h
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "struct timespec \fBrandSleepTime\fP"
.br
.ti -1c
.RI "struct timespec \fBsleepTimeRemaining\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "struct timespec randSleepTime"

.PP
Definition at line \fB1\fP of file \fBnodes\&.h\fP\&.
.SS "struct timespec sleepTimeRemaining"

.PP
Definition at line \fB2\fP of file \fBnodes\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Simulazione Transazioni from the source code\&.
