.TH "parameters" 3 "Thu Jan 13 2022" "Simulazione Transazioni" \" -*- nroff -*-
.ad l
.nh
.SH NAME
parameters
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <common\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBSO_USER_NUM\fP"
.br
.ti -1c
.RI "unsigned int \fBSO_NODES_NUM\fP"
.br
.ti -1c
.RI "unsigned int \fBSO_BUDGET_INIT\fP"
.br
.ti -1c
.RI "char \fBSO_REWARD\fP"
.br
.ti -1c
.RI "unsigned long \fBSO_MIN_TRANS_GEN_NSEC\fP"
.br
.ti -1c
.RI "unsigned long \fBSO_MAX_TRANS_GEN_NSEC\fP"
.br
.ti -1c
.RI "unsigned int \fBSO_RETRY\fP"
.br
.ti -1c
.RI "unsigned int \fBSO_TP_SIZE\fP"
.br
.ti -1c
.RI "unsigned long \fBSO_MIN_TRANS_PROC_NSEC\fP"
.br
.ti -1c
.RI "unsigned long \fBSO_MAX_TRANS_PROC_NSEC\fP"
.br
.ti -1c
.RI "unsigned int \fBSO_SIM_SEC\fP"
.br
.ti -1c
.RI "unsigned int \fBSO_FRIENDS_NUM\fP"
.br
.ti -1c
.RI "unsigned int \fBSO_HOPS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB77\fP of file \fBcommon\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "unsigned int SO_BUDGET_INIT"

.PP
Definition at line \fB81\fP of file \fBcommon\&.h\fP\&.
.SS "unsigned int SO_FRIENDS_NUM"

.PP
Definition at line \fB90\fP of file \fBcommon\&.h\fP\&.
.SS "unsigned int SO_HOPS"

.PP
Definition at line \fB91\fP of file \fBcommon\&.h\fP\&.
.SS "unsigned long SO_MAX_TRANS_GEN_NSEC"

.PP
Definition at line \fB84\fP of file \fBcommon\&.h\fP\&.
.SS "unsigned long SO_MAX_TRANS_PROC_NSEC"

.PP
Definition at line \fB88\fP of file \fBcommon\&.h\fP\&.
.SS "unsigned long SO_MIN_TRANS_GEN_NSEC"

.PP
Definition at line \fB83\fP of file \fBcommon\&.h\fP\&.
.SS "unsigned long SO_MIN_TRANS_PROC_NSEC"

.PP
Definition at line \fB87\fP of file \fBcommon\&.h\fP\&.
.SS "unsigned int SO_NODES_NUM"

.PP
Definition at line \fB80\fP of file \fBcommon\&.h\fP\&.
.SS "unsigned int SO_RETRY"

.PP
Definition at line \fB85\fP of file \fBcommon\&.h\fP\&.
.SS "char SO_REWARD"

.PP
Definition at line \fB82\fP of file \fBcommon\&.h\fP\&.
.SS "unsigned int SO_SIM_SEC"

.PP
Definition at line \fB89\fP of file \fBcommon\&.h\fP\&.
.SS "unsigned int SO_TP_SIZE"

.PP
Definition at line \fB86\fP of file \fBcommon\&.h\fP\&.
.SS "unsigned int SO_USER_NUM"

.PP
Definition at line \fB79\fP of file \fBcommon\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Simulazione Transazioni from the source code\&.
