.TH "src/parser.c" 3 "Thu Jan 13 2022" "Simulazione Transazioni" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/parser.c
.SH SYNOPSIS
.br
.PP
\fC#include 'include/common\&.h'\fP
.br
\fC#include 'utils/debug\&.h'\fP
.br
\fC#include 'include/parser\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBassign_defaults\fP (struct \fBparameters\fP *\fBpar\fP)"
.br
.ti -1c
.RI "int \fBparse_parameters\fP (struct \fBparameters\fP *\fBpar\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void assign_defaults (struct \fBparameters\fP * par)"

.PP
Definition at line \fB41\fP of file \fBparser\&.c\fP\&.
.SS "int parse_parameters (struct \fBparameters\fP * par)"

.PP
Definition at line \fB58\fP of file \fBparser\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Simulazione Transazioni from the source code\&.
