.TH "src/include/parser.h" 3 "Thu Jan 13 2022" "Simulazione Transazioni" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/parser.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNUM_PARAMETERS\fP   13"
.br
.ti -1c
.RI "#define \fBCONF_FILE\fP   'conf\&.txt'"
.br
.ti -1c
.RI "#define \fBCONF_ERROR\fP   \-1"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBparse_parameters\fP (struct \fBparameters\fP *\fBpar\fP)"
.br
.ti -1c
.RI "void \fBassign_defaults\fP (struct \fBparameters\fP *\fBpar\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CONF_ERROR   \-1"

.PP
Definition at line \fB9\fP of file \fBparser\&.h\fP\&.
.SS "#define CONF_FILE   'conf\&.txt'"

.PP
Definition at line \fB8\fP of file \fBparser\&.h\fP\&.
.SS "#define NUM_PARAMETERS   13"

.PP
Definition at line \fB7\fP of file \fBparser\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void assign_defaults (struct \fBparameters\fP * par)"

.PP
Definition at line \fB41\fP of file \fBparser\&.c\fP\&.
.SS "int parse_parameters (struct \fBparameters\fP * par)"

.PP
Definition at line \fB58\fP of file \fBparser\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Simulazione Transazioni from the source code\&.
