.TH "src/include/print.h" 3 "Thu Jan 13 2022" "Simulazione Transazioni" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/print.h
.SH SYNOPSIS
.br
.PP
\fC#include 'common\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprint_time_to_die\fP ()"
.br
.ti -1c
.RI "void \fBprint_user_nodes_table\fP (pid_t \fBmain\fP, \fBuser\fP *\fBuser\fP, \fBnode\fP *nodes, struct \fBparameters\fP *\fBpar\fP)"
.br
.ti -1c
.RI "void \fBprint_kill_signal\fP ()"
.br
.ti -1c
.RI "void \fBprint_user_balance\fP ()"
.br
.ti -1c
.RI "void \fBprint_node_balance\fP ()"
.br
.ti -1c
.RI "void \fBprint_num_aborted\fP ()"
.br
.ti -1c
.RI "void \fBprint_num_blocks\fP ()"
.br
.ti -1c
.RI "void \fBprint_transactions_still_in_pool\fP ()"
.br
.ti -1c
.RI "void \fBfinal_print\fP (pid_t masterPID, \fBuser\fP *\fBusersPID\fP, \fBnode\fP *\fBnodesPID\fP, struct \fBparameters\fP *\fBpar\fP)"
.br
.ti -1c
.RI "void \fBprint_parameters\fP (struct \fBparameters\fP *\fBpar\fP)"
.br
.ti -1c
.RI "void \fBprint_block\fP (FILE *fp, \fBblock\fP *b)"
.br
.ti -1c
.RI "void \fBprint_transaction\fP (FILE *fp, \fBtransaction\fP *t)"
.br
.ti -1c
.RI "void \fBprint_ledger\fP (\fBledger\fP *l)"
.br
.ti -1c
.RI "void \fBformatted_timestamp\fP (FILE *fp)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void final_print (pid_t masterPID, \fBuser\fP * usersPID, \fBnode\fP * nodesPID, struct \fBparameters\fP * par)"

.PP
Definition at line \fB40\fP of file \fBprint\&.c\fP\&.
.SS "void formatted_timestamp (FILE * fp)"

.PP
Definition at line \fB157\fP of file \fBprint\&.c\fP\&.
.SS "void print_block (FILE * fp, \fBblock\fP * b)"

.PP
Definition at line \fB127\fP of file \fBprint\&.c\fP\&.
.SS "void print_kill_signal ()"

.SS "void print_ledger (\fBledger\fP * l)"

.PP
Definition at line \fB143\fP of file \fBprint\&.c\fP\&.
.SS "void print_node_balance ()"

.SS "void print_num_aborted ()"

.SS "void print_num_blocks ()"

.SS "void print_parameters (struct \fBparameters\fP * par)"

.PP
Definition at line \fB52\fP of file \fBprint\&.c\fP\&.
.SS "void print_time_to_die ()"

.PP
Definition at line \fB7\fP of file \fBprint\&.c\fP\&.
.SS "void print_transaction (FILE * fp, \fBtransaction\fP * t)"

.PP
Definition at line \fB98\fP of file \fBprint\&.c\fP\&.
.SS "void print_transactions_still_in_pool ()"

.SS "void print_user_balance ()"

.SS "void print_user_nodes_table (pid_t main, \fBuser\fP * user, \fBnode\fP * nodes, struct \fBparameters\fP * par)"

.PP
Definition at line \fB12\fP of file \fBprint\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Simulazione Transazioni from the source code\&.
