.TH "src/utils/sem.c" 3 "Thu Jan 13 2022" "Simulazione Transazioni" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/utils/sem.c
.SH SYNOPSIS
.br
.PP
\fC#include 'sem\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTEST_ERROR\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBsem_set_val\fP (int sem_id, int sem_num, int sem_val)"
.br
.ti -1c
.RI "int \fBsem_reserve\fP (int sem_id, int sem_num)"
.br
.ti -1c
.RI "int \fBsem_release\fP (int sem_id, int sem_num)"
.br
.ti -1c
.RI "int \fBsem_getall\fP (char *my_string, int sem_id)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBerrno\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TEST_ERROR"
\fBValue:\fP
.PP
.nf
    if (errno)                                     \
    {                                              \
        fprintf(stderr,                            \
                "%s:%d: PID=%5d: Error %d (%s)\n", \
                __FILE__,                          \
                __LINE__,                          \
                getpid(),                          \
                errno,                             \
                strerror(errno));                  \
    }
.fi
.PP
Definition at line \fB4\fP of file \fBsem\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int sem_getall (char * my_string, int sem_id)"

.PP
Definition at line \fB49\fP of file \fBsem\&.c\fP\&.
.SS "int sem_release (int sem_id, int sem_num)"

.PP
Definition at line \fB37\fP of file \fBsem\&.c\fP\&.
.SS "int sem_reserve (int sem_id, int sem_num)"

.PP
Definition at line \fB26\fP of file \fBsem\&.c\fP\&.
.SS "int sem_set_val (int sem_id, int sem_num, int sem_val)"

.PP
Definition at line \fB20\fP of file \fBsem\&.c\fP\&.
.SH "Variable Documentation"
.PP 
.SS "int errno"

.PP
Definition at line \fB17\fP of file \fBsem\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Simulazione Transazioni from the source code\&.
