.TH "semun" 3 "Thu Jan 13 2022" "Simulazione Transazioni" \" -*- nroff -*-
.ad l
.nh
.SH NAME
semun
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sem\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBval\fP"
.br
.ti -1c
.RI "struct semid_ds * \fBbuf\fP"
.br
.ti -1c
.RI "unsigned short * \fBarray\fP"
.br
.ti -1c
.RI "struct seminfo * \fB__buf\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB31\fP of file \fBsem\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "struct seminfo* __buf"

.PP
Definition at line \fB35\fP of file \fBsem\&.h\fP\&.
.SS "unsigned short* array"

.PP
Definition at line \fB34\fP of file \fBsem\&.h\fP\&.
.SS "struct semid_ds* buf"

.PP
Definition at line \fB33\fP of file \fBsem\&.h\fP\&.
.SS "int val"

.PP
Definition at line \fB32\fP of file \fBsem\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Simulazione Transazioni from the source code\&.
