.TH "src/users.c" 3 "Thu Jan 13 2022" "Simulazione Transazioni" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/users.c
.SH SYNOPSIS
.br
.PP
\fC#include 'include/common\&.h'\fP
.br
\fC#include 'include/users\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBREWARD\fP(amount,  reward)   (ceil(((reward * (amount)) / 100\&.0)))"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBget_pid_userIndex\fP (int PID_toSearch)"
.br
.ti -1c
.RI "pid_t \fBget_random_userPID\fP ()"
.br
.ti -1c
.RI "pid_t \fBget_random_nodePID\fP ()"
.br
.ti -1c
.RI "void \fBupdate_status\fP (int statusToSet)"
.br
.ti -1c
.RI "void \fBattach_ipc_objects\fP (char **argv)"
.br
.ti -1c
.RI "void \fBqueue_to_pid\fP (pid_t nodePID)"
.br
.ti -1c
.RI "void \fBtransaction_init\fP (pid_t userPID, int amount, int reward)"
.br
.ti -1c
.RI "void \fBsignal_handlers_init\fP (struct sigaction *saUSR1, struct sigaction *saINT)"
.br
.ti -1c
.RI "int \fBsend_transaction\fP ()"
.br
.ti -1c
.RI "void \fBuser_transactions_handle\fP (int signum)"
.br
.ti -1c
.RI "void \fBuser_interrupt_handle\fP (int signum)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBparameters\fP * \fBpar\fP"
.br
.ti -1c
.RI "\fBuser\fP * \fBusersPID\fP"
.br
.ti -1c
.RI "\fBnode\fP * \fBnodesPID\fP"
.br
.ti -1c
.RI "\fBledger\fP * \fBmainLedger\fP"
.br
.ti -1c
.RI "int \fBsemID\fP"
.br
.ti -1c
.RI "int \fBqueueID\fP"
.br
.ti -1c
.RI "int \fBcurrBalance\fP"
.br
.ti -1c
.RI "pid_t \fBmyPID\fP"
.br
.ti -1c
.RI "int \fBoutGoingTransactions\fP"
.br
.ti -1c
.RI "\fBtransaction\fP \fBcurrTrans\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define REWARD(amount, reward)   (ceil(((reward * (amount)) / 100\&.0)))"

.PP
Definition at line \fB4\fP of file \fBusers\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void attach_ipc_objects (char ** argv)"

.PP
Definition at line \fB120\fP of file \fBusers\&.c\fP\&.
.SS "int get_pid_userIndex (int PID_toSearch)"

.PP
Definition at line \fB51\fP of file \fBusers\&.c\fP\&.
.SS "pid_t get_random_nodePID ()"

.PP
Definition at line \fB83\fP of file \fBusers\&.c\fP\&.
.SS "pid_t get_random_userPID ()"

.PP
Definition at line \fB65\fP of file \fBusers\&.c\fP\&.
.SS "int main (int argc, char * argv[])"

.PP
Definition at line \fB233\fP of file \fBusers\&.c\fP\&.
.SS "void queue_to_pid (pid_t nodePID)"

.PP
Definition at line \fB138\fP of file \fBusers\&.c\fP\&.
.SS "int send_transaction ()"

.PP
Definition at line \fB176\fP of file \fBusers\&.c\fP\&.
.SS "void signal_handlers_init (struct sigaction * saUSR1, struct sigaction * saINT)"

.PP
Definition at line \fB160\fP of file \fBusers\&.c\fP\&.
.SS "void transaction_init (pid_t userPID, int amount, int reward)"

.PP
Definition at line \fB146\fP of file \fBusers\&.c\fP\&.
.SS "void update_status (int statusToSet)"

.PP
Definition at line \fB101\fP of file \fBusers\&.c\fP\&.
.SS "void user_interrupt_handle (int signum)"

.PP
Definition at line \fB227\fP of file \fBusers\&.c\fP\&.
.SS "void user_transactions_handle (int signum)"

.PP
Definition at line \fB217\fP of file \fBusers\&.c\fP\&.
.SH "Variable Documentation"
.PP 
.SS "int currBalance"

.PP
Definition at line \fB39\fP of file \fBusers\&.c\fP\&.
.SS "\fBtransaction\fP currTrans"

.PP
Definition at line \fB42\fP of file \fBusers\&.c\fP\&.
.SS "\fBledger\fP* mainLedger"

.PP
Definition at line \fB34\fP of file \fBusers\&.c\fP\&.
.SS "pid_t myPID"

.PP
Definition at line \fB40\fP of file \fBusers\&.c\fP\&.
.SS "\fBnode\fP* nodesPID"

.PP
Definition at line \fB33\fP of file \fBusers\&.c\fP\&.
.SS "int outGoingTransactions"

.PP
Definition at line \fB41\fP of file \fBusers\&.c\fP\&.
.SS "struct \fBparameters\fP* par"

.PP
Definition at line \fB31\fP of file \fBusers\&.c\fP\&.
.SS "int queueID"

.PP
Definition at line \fB37\fP of file \fBusers\&.c\fP\&.
.SS "int semID"

.PP
Definition at line \fB36\fP of file \fBusers\&.c\fP\&.
.SS "\fBuser\fP* usersPID"

.PP
Definition at line \fB32\fP of file \fBusers\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Simulazione Transazioni from the source code\&.
