.TH "user_t" 3 "Thu Jan 13 2022" "Simulazione Transazioni" \" -*- nroff -*-
.ad l
.nh
.SH NAME
user_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <common\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBalive\fP, \fBbroke\fP, \fBdead\fP }"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "pid_t \fBpid\fP"
.br
.ti -1c
.RI "enum user_t:: { \&.\&.\&. }  \fBstatus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB94\fP of file \fBcommon\&.h\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIalive \fP\fP
.TP
\fB\fIbroke \fP\fP
.TP
\fB\fIdead \fP\fP
.PP
Definition at line \fB97\fP of file \fBcommon\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "pid_t pid"

.PP
Definition at line \fB96\fP of file \fBcommon\&.h\fP\&.
.SS "enum  { \&.\&.\&. }  status"


.SH "Author"
.PP 
Generated automatically by Doxygen for Simulazione Transazioni from the source code\&.
