.TH "block_t" 3 "Thu Jan 13 2022" "Simulazione-Transazioni" \" -*- nroff -*-
.ad l
.nh
.SH NAME
block_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBtransaction\fP \fBtransList\fP [SO_BLOCK_SIZE]"
.br
.ti -1c
.RI "unsigned int \fBblockIndex\fP"
.br
.ti -1c
.RI "struct \fBblock\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBblock\fP * \fBprev\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Simulazione-Transazioni from the source code\&.
