.TH "ledger_t" 3 "Thu Jan 13 2022" "Simulazione-Transazioni" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ledger_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBblock\fP * \fBhead\fP"
.br
.ti -1c
.RI "unsigned int \fBregistryCurrSize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Simulazione-Transazioni from the source code\&.
