.TH "message" 3 "Thu Jan 13 2022" "Simulazione-Transazioni" \" -*- nroff -*-
.ad l
.nh
.SH NAME
message
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "long \fBmtype\fP"
.br
.ti -1c
.RI "\fBtransaction\fP \fBuserTrans\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Simulazione-Transazioni from the source code\&.
