.TH "parameters" 3 "Thu Jan 13 2022" "Simulazione-Transazioni" \" -*- nroff -*-
.ad l
.nh
.SH NAME
parameters
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBSO_USER_NUM\fP"
.br
.ti -1c
.RI "unsigned int \fBSO_NODES_NUM\fP"
.br
.ti -1c
.RI "unsigned int \fBSO_BUDGET_INIT\fP"
.br
.ti -1c
.RI "char \fBSO_REWARD\fP"
.br
.ti -1c
.RI "unsigned long \fBSO_MIN_TRANS_GEN_NSEC\fP"
.br
.ti -1c
.RI "unsigned long \fBSO_MAX_TRANS_GEN_NSEC\fP"
.br
.ti -1c
.RI "unsigned int \fBSO_RETRY\fP"
.br
.ti -1c
.RI "unsigned int \fBSO_TP_SIZE\fP"
.br
.ti -1c
.RI "unsigned long \fBSO_MIN_TRANS_PROC_NSEC\fP"
.br
.ti -1c
.RI "unsigned long \fBSO_MAX_TRANS_PROC_NSEC\fP"
.br
.ti -1c
.RI "unsigned int \fBSO_SIM_SEC\fP"
.br
.ti -1c
.RI "unsigned int \fBSO_FRIENDS_NUM\fP"
.br
.ti -1c
.RI "unsigned int \fBSO_HOPS\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Simulazione-Transazioni from the source code\&.
