.TH "semun" 3 "Thu Jan 13 2022" "Simulazione-Transazioni" \" -*- nroff -*-
.ad l
.nh
.SH NAME
semun
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBval\fP"
.br
.ti -1c
.RI "struct semid_ds * \fBbuf\fP"
.br
.ti -1c
.RI "unsigned short * \fBarray\fP"
.br
.ti -1c
.RI "struct seminfo * \fB__buf\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Simulazione-Transazioni from the source code\&.
